import 'package:flutter_lakshman1020/features/home/models/shipment_model.dart';
import 'package:fl_chart/fl_chart.dart';

final List<Shipment> shipments = [
  Shipment(
    id: "load_45982",
    title: "#load_45982",
    description: "Medical equipment for students",
    origin: "Chicago, IL",
    destination: "Indianapolis, IN",
    status: "",
  ),
  Shipment(
    id: "load_45983",
    title: "#load_45983",
    description: "Electronics components",
    origin: "New York, NY",
    destination: "Los Angeles, CA",
  ),
  Shipment(
    id: "load_45984",
    title: "#load_45984",
    description: "Food supplies",
    origin: "Houston, TX",
    destination: "Miami, FL",
    status: "false",
  ),
  Shipment(
    id: "load_45985",
    title: "#load_45985",
    description: "Construction materials",
    origin: "Seattle, WA",
    destination: "Portland, OR",
    status: "true",
  ),
  Shipment(
    id: "load_45986",
    title: "#load_45986",
    description: "Clothing and textiles",
    origin: "Boston, MA",
    destination: "Atlanta, GA",
    status: "false",
  ),
  Shipment(
    id: "load_45982",
    title: "#load_45982",
    description: "Medical equipment for students",
    origin: "Chicago, IL",
    destination: "Indianapolis, IN",
    status: "false",
  ),
  Shipment(
    id: "load_45983",
    title: "#load_45983",
    description: "Electronics components",
    origin: "New York, NY",
    destination: "Los Angeles, CA",
  ),
  Shipment(
    id: "load_45984",
    title: "#load_45984",
    description: "Food supplies",
    origin: "Houston, TX",
    destination: "Miami, FL",
    status: "false",
  ),
  Shipment(
    id: "load_45985",
    title: "#load_45985",
    description: "Construction materials",
    origin: "Seattle, WA",
    destination: "Portland, OR",
    status: "true",
  ),
  Shipment(
    id: "load_45986",
    title: "#load_45986",
    description: "Clothing and textiles",
    origin: "Boston, MA",
    destination: "Atlanta, GA",
    status: "false",
  ),
  Shipment(
    id: "load_45982",
    title: "#load_45982",
    description: "Medical equipment for students",
    origin: "Chicago, IL",
    destination: "Indianapolis, IN",
    status: "false",
  ),
  Shipment(
    id: "load_45983",
    title: "#load_45983",
    description: "Electronics components",
    origin: "New York, NY",
    destination: "Los Angeles, CA",
  ),
];

final Map<String, List<FlSpot>> chartData = {
  "daily": [
    FlSpot(0, 1),
    FlSpot(1, 3),
    FlSpot(2, 2.5),
    FlSpot(3, 4),
    FlSpot(4, 3.5),
    FlSpot(5, 5),
    FlSpot(6, 4),
  ],
  "weekly": [
    FlSpot(0, 1.5),
    FlSpot(1, 1),
    FlSpot(2, 2),
    FlSpot(3, 1),
    FlSpot(4, 3),
    FlSpot(5, 2.5),
    FlSpot(6, 2),
  ],
  "monthly": [
    FlSpot(0, 2),
    FlSpot(1, 2.5),
    FlSpot(2, 3),
    FlSpot(3, 2),
    FlSpot(3, 3.5),
    FlSpot(5, 2.8),
    FlSpot(6, 4),
  ],
};
